language: java
jdk:
- oraclejdk8
- oraclejdk9
dist: trusty
services:
- docker
env:
  matrix:
  - COVERAGE=0.05 BUILD_TARGET=./monolithic/ui
  - COVERAGE=0.14 BUILD_TARGET=./monolithic/service/cart
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/service/user
  - COVERAGE=0.36 BUILD_TARGET=./monolithic/repository/order
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/cart
  - COVERAGE=0.12 BUILD_TARGET=./monolithic/repository/product
  - COVERAGE=0.31 BUILD_TARGET=./monolithic/repository/user
  global:
  - secure: KqRwS2UIyTsI78zlv4XTGru9kh4ICP+zLqzBHpbBXdAMJIeN/cdRLK9OVAQRZim10Qs5sUSt+VEw0tcomVITUmcrtfopVSXJg/g8jMuy66Ixr+1d7IwwpMsZe/3wMCuL71YvtDqMMkZTTXFe6r3PDW5dt68X/R6hLWXUiqNXjINrbBJObXYYs3q41rn/X4zgdmz9aoCuXy9eT3ljNQJdOh9XKv02vX98gCb4jgxpCI77/vk36GQbSxzqNDbRciIstIRbw6/knbIOTJR3vq7LR3I+UzLLF3C77qiHQgWhkmnaE+jHPLcTxF7UcI5PMQCp5xbSOh8T+TZhtT8Q5D2aRL2VLh/Xr0f+DWDjV48tfi07UlehHKwPQfu26yQjXb7Bg5KHgnJOyrCzcHTgTRS2TtVYCtV3bAINR/xXqI86RVg6xzWFbQ35MCfIOdD/dTFCI4dLre/V/srRusWL7Ttmdk7dou+n8ek3bWyaqKGTYBxrWAkXypDXDeRF2c708Z88urGxNuZ22oSJiYI2qsJ6cZWx8a0GNH+BNENBY51Sy08eN0BNX8On+UrncYzDPEcuDFTWWVm5ylZu0+yGNe97B2sacXY5pASd62lv6l0dB1RbqxB9I98ImhGQjHwgiSDbXIsW82j+6HCyX8FBcoY37ensN+JvwKIQdJw2ETKaV5k=
  - secure: hgUZPFPFEVfIJ3jKZD+AMUI75XnCq2CRWDYVDlCaIDhEfJUCAkBI1PB/AZDhvLSLI+mbtKwxkpo464RGZcC79Asgxn2Qu9gOpsIsLnyfoMpR/tsIotIoEpTqs7KHE/h8krgoMm8u1Ein708fBSP7dUF2Li7VkNt0rMHq/iIGo5zk6Hxt9RSSSzpkxdw2xAYCt50GtClQ8nvs3YfT/f/AAX12DdZmERiEf+jprqMrpeqtkZ4ocqygBoiZN4v0OdTPm/fFDg3HAJIzK4c2DgSOW+GGE9vVfd3SIv5YVliguKC2dQJHh/ud5fKJleMXuTU2Ql6hErIDGaw9K5cii9dGGSfZ15a41zfhTMf+iiWtgcJF+S7Hk0XMR5LDv2svrd2vJZOcS7SMYcgPYTdJL71ehz9AAbS7SKnJsvHWboEaKd4gQJNrY740MNxVAY6sLzUlaFln4pITcpVMfa66oOSdxaj4ag+VijCqwwRHn07GD8lv5r2TxPDzgPHElVDPtzFOlqFkwlWLV7kbhRjYA5W0A17/DTNpxjLPl4vrOUUhcj9ItmxD7oTSEKIH4qxCM0mWgiBAs/fLNzoKIXZmVKIC2Dr4LqXTavBI+zUvEgr0R1G5trDBgO3Wyy6cjwm+Qz0vDuR4uFEeqHrx9Q1mKZuIqfrAC9klfUZ88DwNleGqmRY=
install:
- "./gradlew clean jar"
script:
- "./gradlew -p $BUILD_TARGET check"
before deploy:
  - "./gradlew -p ./monolithic/ui packageToContainer"
deploy:
  provider: script
  script: "./script/deploy.sh"
  on:
    branch: master
    condition: $BUILD_TARGET=./monolithic/ui

