language: java
jdk:
  - oraclejdk8
dist: trusty

install:
  - ./gradlew clean jar

script:
  - ./gradlew test

before deploy:
  - ./gradlew test jacocoTestCoverageVerification

after success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true