language: java
jdk:
  - oraclejdk8
dist: trusty

env:
  - COVERAGE=0.05 BUILD_TARGET=./monolithic/ui
  - COVERAGE=0.14 BUILD_TARGET=./monolithic/service/cart
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/service/user
  - COVERAGE=0.36 BUILD_TARGET=./monolithic/repository/order
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/cart
  - COVERAGE=0.12 BUILD_TARGET=./monolithic/repository/product
  - COVERAGE=0.31 BUILD_TARGET=./monolithic/repository/user

install:
  - ./gradlew clean jar

script:
  - ./gradlew test $BUILD_TARGET

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true